name: Rust build

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    tags:
      - "v*"
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: "Build wasm32"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      - name: Build with trunk
        run: |
          trunk build --release
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.docker_registry }}/sand-bevy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/sand-bevy:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/sand-bevy:buildcache,mode=max
